version: "3.7"
services:
  gim_model:
    restart: "no"
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      # bind . on host to /home/root in container (allows editing code)
      #- .:/home/root
      - type: bind
        source: .
        target: /home/root
        #volume:
        #  nocopy: true
      # bind data drives
      - type: bind
        source: ./data
        target: /home/root/data

      - type: bind
        source: ./saved_models/ebs_trained_models
        target: /home/root/saved_models/ebs_trained_models

      - type: bind
        source: ./results
        target: /home/root/results

      - type: bind
        source: ./processed
        target: /home/root/processed



